version: 2

# Define the jobs we want to run for this project
jobs:
  deploy:
    docker:
      - image: circleci/node@2.0.2
    steps:
      - npm build
      - npm test

workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 13.11.0
      - node/test:
          version: 12.16.0
      - node/test:
          version: 10.19.0      
      - deploy:
          command: bash <(curl -s https://copilot.blackducksoftware.com/ci/circle2/scripts/upload)
